import { Milestone } from './types';

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: '1',
    title: 'Acquisition premier lot de terrain',
    date: '2022-03-15',
    year: 2022,
    type: 'Lot de terrain',
    value: 45000,
    circumstances: 'Héritage familial + emprunt bancaire',
    imageUrl: 'https://picsum.photos/seed/land1/200/200',
    color: 'var(--color-accent-green)',
    lineWidth: 4,
  },
  {
    id: '2',
    title: 'Investissement portefeuille actions',
    date: '2023-06-10',
    year: 2023,
    type: 'Investissement financier',
    value: 120000,
    circumstances: 'Épargne personnelle + bonus annuel',
    imageUrl: 'https://picsum.photos/seed/stocks/200/200',
    color: 'var(--color-accent-blue)',
    lineWidth: 2,
  },
  {
    id: '3',
    title: 'Achat appartement locatif',
    date: '2024-09-20',
    year: 2024,
    type: 'Acquisition immobilière',
    value: 285000,
    circumstances: 'Crédit immobilier sur 20 ans',
    imageUrl: 'https://picsum.photos/seed/building/200/200',
    color: 'var(--color-accent-orange)',
    lineWidth: 6,
  },
  {
    id: '4',
    title: 'Création SCI familiale',
    date: '2025-01-05',
    year: 2025,
    type: 'Autre',
    value: 0,
    circumstances: 'Optimisation fiscale et transmission',
    imageUrl: 'https://picsum.photos/seed/document/200/200',
    color: 'var(--color-accent-purple)',
    lineWidth: 3,
  },
  {
    id: '5',
    title: 'Rénovation et revente terrain',
    date: '2027-11-12',
    year: 2027,
    type: 'Lot de terrain',
    value: 95000,
    circumstances: 'Plus-value après travaux de viabilisation',
    imageUrl: 'https://picsum.photos/seed/renovation/200/200',
    color: 'var(--color-accent-gold)',
    lineWidth: 5,
  },
  {
    id: '6',
    title: 'Nouvel investissement terrain agricole',
    date: '2029-04-18',
    year: 2029,
    type: 'Lot de terrain',
    value: 78000,
    circumstances: 'Diversification vers le foncier rural',
    imageUrl: 'https://picsum.photos/seed/tractor/200/200',
    color: 'var(--color-accent-brown)',
    lineWidth: 4,
  },
  {
    id: '7',
    title: 'Objectif : 1 million € de patrimoine',
    date: '2031-12-31',
    year: 2031,
    type: 'Autre',
    value: 1000000,
    circumstances: 'Projection de croissance du portefeuille',
    imageUrl: 'https://picsum.photos/seed/trophy/200/200',
    color: 'var(--color-accent-teal)',
    lineWidth: 8,
  },
  {
    id: '8',
    title: 'Retraite anticipée',
    date: '2035-01-01',
    year: 2035,
    type: 'Autre',
    value: 0,
    circumstances: 'Indépendance financière atteinte',
    imageUrl: 'https://picsum.photos/seed/beach/200/200',
    color: 'var(--color-accent-teal)',
    lineWidth: 10,
  },
];
